name: zenrouter_dartnative
description: Native navigation, route presentations, and persistent layouts for ZenRouter on DartNative.
version: 0.1.1

repository: https://github.com/definev/zenrouter
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter_dartnative
issue_tracker: https://github.com/definev/zenrouter/issues

topics:
  - router
  - navigation
  - dartnative
  - zenrouter

environment:
  sdk: ^3.9.0

dependencies:
  dartnative: ^1.0.0
  zenrouter_core: ^3.0.0

dev_dependencies:
  test: ^1.25.0
